"""empty message

Revision ID: 07c562be95e8
Revises: 82fe166995f1
Create Date: 2024-11-23 22:29:24.482739

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07c562be95e8'
down_revision = '82fe166995f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fakenodo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('conceptrecid', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fakenodo', schema=None) as batch_op:
        batch_op.drop_column('conceptrecid')

    # ### end Alembic commands ###
