"""empty message

Revision ID: 82fe166995f1
Revises: 2f50029c5de8
Create Date: 2024-11-23 21:57:50.580149

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82fe166995f1'
down_revision = '2f50029c5de8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fakenodo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fakenodo_creator',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('affiliation', sa.String(length=255), nullable=True),
    sa.Column('orcid', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fakenodo_file',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('fakenodo_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['fakenodo_id'], ['fakenodo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fakenodo_metadata',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('publication_type', sa.String(length=255), nullable=True),
    sa.Column('publication_date', sa.DateTime(), nullable=True),
    sa.Column('access_right', sa.String(length=255), nullable=True),
    sa.Column('license', sa.String(length=255), nullable=True),
    sa.Column('fakenodo_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['fakenodo_id'], ['fakenodo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fakenodo_metadata_creator',
    sa.Column('fakenodo_metadata_id', sa.Integer(), nullable=True),
    sa.Column('fakenodo_creator_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['fakenodo_creator_id'], ['fakenodo_creator.id'], ),
    sa.ForeignKeyConstraint(['fakenodo_metadata_id'], ['fakenodo_metadata.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fakenodo_metadata_creator')
    op.drop_table('fakenodo_metadata')
    op.drop_table('fakenodo_file')
    op.drop_table('fakenodo_creator')
    op.drop_table('fakenodo')
    # ### end Alembic commands ###
